name: Run My Script

on: [push]

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Python script
      run: pip install -f requirements.txt
      run: python fuzz.py